### ISSUE TITLE
error link does not give a real error object, thus no networkError.statusCode access possible

### ISSUE THREAD

**Issue by miracle2k** [apollographql/apollo-link#218]
I am basically using this example from the docs ("Afterware"): https://www.apollographql.com/docs/react/basics/network-layer.html

``` 
import ApolloClient from 'apollo-client';
import { HttpLink } from 'apollo-link-http';
import { onError } from 'apollo-link-error'
import { logout } from './logout';
const httpLink = new HttpLink({ uri: '/graphql' });
const logoutLink = onError(({ networkError }) => {
  if (networkError.statusCode === 401) logout();
})
const client = new ApolloClient({
  link: logoutLink.concat(httpLink),
});
```

This doesn't work for me. "networkError" seems to be raised as a string, and only tells me "Failed to fetch". It doesn't have a stack, nor the .statusCode property.

https://www.webpackbin.com/bins/-KyLJ0NyjpkxU0ggok70

**Comment by maurodelazeri** [comment]
+1 

the way I'm solving this temporarily is by picking up the status directly on the component that makes the call


  componentWillReceiveProps(nextProps) {
    console.log(
      "life cycle: componentWillReceiveProps",
      nextProps.data.networkStatus
    );
  }

ex:
7 = 200
8 = 401

**Comment by leethree** [comment]
Yes, the `networkError` object is not very helpful and the `response` object is missing. There's no way to handle HTTP status codes in network layer.

**Comment by tjpeden** [comment]
This is kind of a big deal, I haven't found a solution for angular

**Comment by jbaxleyiii** [comment]
@miracle2k we are working to improve errors with https://github.com/apollographql/apollo-link/pull/244, does it look like it will fix your issue?

**Comment by miracle2k** [comment]
@jbaxleyiii Not sure, but a quick scan of the patch set doesn't lead me to conclude that it changes the object that `networkError` is; if you look at the webpackbin link I put above, this seems to be a string, which means we don't know the status code.

**Comment by tjpeden** [comment]
@miracle2k Looks like they added test coverage around 401 (which is what I think you mean) so hopefully that means the things they changed actually produce a result containing the status code.

I would like to point out, however, that your webpackbin demonstrates (for me at least) that `networkError.statusCode` is undefined, not a string. That behavior is consistent with my findings as well though. I have hope that this patch fixes that issue.

**Comment by yuricamara** [comment]
## The problem and the solution

```
export interface ErrorResponse {
  graphQLErrors?: GraphQLError[];
  networkError?: Error;
  response?: ExecutionResult;
  operation: Operation;
}
```
from https://github.com/apollographql/apollo-link/blob/98eeb1deb0363384f291822b6c18cdc2c97e5bdb/packages/apollo-link-error/src/index.ts#L4

Error in "networkError?: Error" should be HttpErrorResponse

## A workaround

```
    const errorLink = onError(({ networkError }) => {
      const networkErrorRef:HttpErrorResponse = networkError as HttpErrorResponse;
      if (networkErrorRef && networkErrorRef.status === 401) {
        console.log('Going to login page...');
      }
    });
```

**Comment by yuricamara** [comment]
## The problem and the solution (I guess)

```
export interface ErrorResponse {
  graphQLErrors?: GraphQLError[];
  networkError?: Error;
  response?: ExecutionResult;
  operation: Operation;
}
```
from https://github.com/apollographql/apollo-link/blob/98eeb1deb0363384f291822b6c18cdc2c97e5bdb/packages/apollo-link-error/src/index.ts#L4

Error in "networkError?: Error" should be like HttpErrorResponse from Angular


## A workaround
### With Angular
```
   import { HttpErrorResponse } from '@angular/common/http';	

    const errorLink = onError(({ networkError }) => {
      const networkErrorRef:HttpErrorResponse = networkError as HttpErrorResponse;
      if (networkErrorRef && networkErrorRef.status === 401) {
        console.log('Going to login page...');
      }
    });
```
### Without Angular
Create the type HttpErrorResponse like [the one from Angular](https://angular.io/api/common/http/HttpErrorResponse) or change it for 'any'
	
    const errorLink = onError(({ networkError }) => {
      const networkErrorRef:HttpErrorResponse = networkError as HttpErrorResponse;
      if (networkErrorRef && networkErrorRef.status === 401) {
        console.log('Going to login page...');
      }
    });

**Comment by jbaxleyiii** [comment]
This should be fixed in the newest release thanks to @evans work!

**Comment by goldenbearkin** [comment]
seems it hasn't fixed.

**Comment by pSchaub** [comment]
@jbaxleyiii I am not able to find the fix. Where is it?

**Comment by miracle2k** [comment]
Same here. I updated the webpackbin above with the latest releases to show that the statusCode is still not accessible.

**Comment by webmobiles** [comment]
yes, please waiting the fix, I've upgraded but have this problem in the real production environment..

**Comment by bogdansoare** [comment]
Also having this issue.

**Comment by akrigline** [comment]
Likewise. @jbaxleyiii It doesn't look like the latest npm releases have this in.

**Comment by polonel** [comment]
Having this issue as well. It is surprising that this is still an ongoing problem after two months.

**Comment by webmobiles** [comment]
apollo looks a  project abandoned, i'm migrating to manual fetch  with javscript

**Comment by evans** [comment]
@webmobiles I'm sorry you feel this way! I hope that we are able to get this fix out quickly

Let's move the conversation to the open issue #300
